In [23]:
import torch

# torch.Tensor的属性

In [ ]:
x = torch.arange(12)
print(f"{x = }")
print(f"{x.shape = }")
print(f"{x.size() = }")
print(f"{x.numel()}")  # 一共有多少个元素
print(f"{x.device = }")
print(f"{x.requires_grad = }")

x = tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])
x.shape = torch.Size([12])
x.size() = torch.Size([12])
12
x.device = device(type='cpu')
x.requires_grad = False


# 创建torch张量

In [ ]:
x = torch.arange(12)
a = x.reshape(2,6)
b = torch.randn(2,4)
c = torch.randint(1,10,(2,3))
d = torch.normal(0,1,(2,2))
e = torch.full((2,2),1)
f = torch.full_like(d,2)
g = torch.ones(2,2)
h = torch.zeros_like(g)
i = torch.tensor([1,2,2,2,2])
j = i.clone()  # 创建副本

# torch.Tensor -> numpy.ndarray

In [26]:
x_np = x.numpy()
x_np

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11], dtype=int64)

In [27]:
x = torch.tensor(x_np)
x, x[2].item()

(tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]), 2)

# torch创建可训练参数

In [28]:
# #### 创建可训练参数 方法1
param0 = torch.arange(3.0, dtype=torch.float32)
param0.requires_grad = True  # float complex  requireds_grad = True
# #### 创建可训练参数 方法2
param1 = torch.nn.Parameter(param0, requires_grad=True)

# torch常用函数

```python
# torch.Tensor  索引、切片、广播 都支持的啊

# 允许广播
torch.matmul()

# # 点乘  向量 向量
torch.dot()

# 矩阵 矩阵
torch.mm()  
A*B
```

# 降维

In [ ]:
A = torch.arange(4).reshape(2,2)
a_sum = A.sum()
print(f"{a_sum = }")

# A.mean()
a_mean = A.sum()/A.numel()  # 同样可以指定axis  降维

a_sum_1 = A.sum(axis=1)  # 同样可以指定axis  降维
print(f"{a_sum_1 = }")
print(f"{a_sum_1.shape = }")

a_sum_01 = A.sum(axis=[0,1])
print(f"{a_sum_01 = }")

a_sum = tensor(6)
a_sum_1 = tensor([1, 5])
a_sum_1.shape = torch.Size([2])
a_sum_01 = tensor(6)


# 非降维求和

In [ ]:
print(a)
a.cumsum(axis=0)

tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]])


tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  8, 10, 12, 14, 16]])

In [33]:
a.cumsum(axis=1)

tensor([[ 0,  1,  3,  6, 10, 15],
        [ 6, 13, 21, 30, 40, 51]])

# 范数

```python
# L1 范数： 绝对值的和
torch.abs(torch.Tesnor).sum()

# L1 范数： 平方和的平方根
torch.norm(torch.Tesnor)

* *优化*（optimization）：用模型拟合观测数据的过程；
* *泛化*（generalization）：数学原理和实践者的智慧，能够指导我们生成出有效性超出用于训练的数据集本身的模型。

# 自动微分

In [ ]:
# Y = 2 X**2 +b
x = torch.arange(6.0)
x.requires_grad_(True)
# x.requires_grad= True 
print(f"{x.grad = }")

x.grad = None


In [ ]:
y = 2 * torch.dot(x,x)
# y = 2 * torch.matmul(x,x)
y

tensor(110., grad_fn=<MulBackward0>)

In [38]:
y.backward()
print(f"{x.grad = }")

x.grad = tensor([ 0.,  4.,  8., 12., 16., 20.])


In [39]:
x.grad == 4 * x

tensor([True, True, True, True, True, True])

In [ ]:
# 在默认情况下torch会累计梯度, 这里需要清除之前的梯度
x.grad.zero_()
y = x.sum()
y.backward()  
x.grad  
# 非标量变量的反向传播
# 反映到每个样本上  --> 每个批次内每个样本的偏导数的和

tensor([1., 1., 1., 1., 1., 1.])

# 分离计算

```python
y_new = y.detach()

In [ ]:
x.grad.zero_()
y = x*x 
u = y.detach()
z = u*x  # z 不是  x ** 3

z.sum().backward()
x.grad == u

tensor([True, True, True, True, True, True])

In [43]:
x.grad.zero_()
y.sum().backward()
x.grad == 2*x

tensor([True, True, True, True, True, True])

# python控制流的梯度计算

In [45]:
def f(a):
    b = a*2
    while b.norm() < 1000:
        b = b*2
    if b.sum() > 0:
        c = b
    else:
        c = 100 * b
    return c 

a = torch.randn(size=(), requires_grad=True)
print(f"{a = }")
d = f(a)
d.backward()

a = tensor(0.4051, requires_grad=True)


In [46]:
a.grad == d/a

tensor(True)