mlp

多项式回归

In [ ]:
import math, torch 
import numpy as np

In [ ]:
# y = 3 + 3.4x - 1.34x**2 + 3.4x**3  + noise
_rank = 9
num_samples = 600
true_w = np.zeros(_rank)
true_w[:4] = np.array([3, 3.4, -1.34, 3.4])

features = np.random.normal(size=(num_samples,1))
np.random.shuffle(features)

labels = np.power(features, np.arange(_rank).reshape(1,-1))
labels = np.dot(labels, true_w)
labels += np.random.normal(size=labels.shape)


true_w, features, labels = [torch.tensor(x,dtype=torch.float32) for x in [true_w, features, labels]]

true_w[:2], features[:2], labels[:2]

(tensor([3.0000, 3.4000]),
 tensor([[ 1.6918],
         [-0.4001]]),
 tensor([19.8735,  0.5263]))