In [1]:
import numpy as np 

In [2]:
arr1 = np.random.randint(0,20, size=(2,2,5))
arr1

array([[[11, 11, 13,  9,  2],
        [ 1,  3,  1,  3,  5]],

       [[ 6, 17, 16,  1,  9],
        [ 8,  2,  4,  5, 13]]])

In [3]:
np.unique(arr1)

array([ 1,  2,  3,  4,  5,  6,  8,  9, 11, 13, 16, 17])

```python
ar：输入数组
return_index：如果为 True，返回原数组中唯一值的索引
return_inverse：如果为 True，返回一个索引数组，可用于重构原始数组
return_counts：如果为 True，返回每个唯一值在原数组中出现的次数
axis：指定沿着哪个轴寻找唯一值

In [4]:
arr1.shape

(2, 2, 5)

In [ ]:
# axis=0    -> arr[0,:,:] arr[1,:,:] 
# axis=1    -> arr[0,0,:] arr[1,0,:]   | arr[0,1,:] arr[0,1,:]
# axis=2 -1 -> arr[01,:,?] arr[01,:,?] | arr[:,01,?] arr[:,01,?] ...

In [ ]:
np.unique(arr1, axis=1) 

array([[[ 1,  3,  1,  3,  5],
        [11, 11, 13,  9,  2]],

       [[ 8,  2,  4,  5, 13],
        [ 6, 17, 16,  1,  9]]])

In [ ]:
np.unique(arr1, axis=1).shape  

(2, 2, 5)

In [ ]:
np.unique(arr1, axis=0)       

array([[[ 6, 17, 16,  1,  9],
        [ 8,  2,  4,  5, 13]],

       [[11, 11, 13,  9,  2],
        [ 1,  3,  1,  3,  5]]])

In [9]:
np.unique(arr1, axis=0).shape

(2, 2, 5)

In [ ]:
np.unique(arr1, axis=2) # axis=2   -> arr[0,0,:]  arr[0,1,:]

array([[[ 2,  9, 11, 11, 13],
        [ 5,  3,  1,  3,  1]],

       [[ 9,  1,  6, 17, 16],
        [13,  5,  8,  2,  4]]])

In [11]:
np.unique(arr1, axis=2).shape

(2, 2, 5)