# **NumPY logs**

In [2]:
import  numpy as np

## np.clip()

- np.clip() 是 NumPy 提供的一个用于 限制数值范围 的函数，常用于深度学习和数值计算中，以 防止溢出或确保数据在合理范围内。
- np.clip() 语法
    ```python
    np.clip(a, a_min, a_max, out=None)
    ## 参数 
    # a：输入的 NumPy 数组。
    # a_min：最小值（可以是标量或数组-match）。
    # a_max：最大值（可以是标量或数组-match）。
    # out（可选）：如果提供，则存储结果，而不创建新的数组。
    ## 返回值
    # 返回一个数组，其中 a 的值被限制在 [a_min, a_max] 之间：
    #   如果 a 的值小于 a_min，则替换为 a_min。
    #   如果 a 的值大于 a_max，则替换为 a_max。
    #   如果 a_min=None，则只应用 a_max 的限制。
    #   如果 a_max=None，则只应用 a_min 的限制。
    ```

In [8]:
arr = np.array([1,2,3,4,5])
arr = np.clip(arr, 1,3)
arr

array([1, 2, 3, 3, 3])

- np.clip() 在深度学习中的应用
    - 防止 log(0) 错误：在交叉熵损失计算时，我们需要 log(y_pred)，但如果 y_pred=0，会导致 log(0) = -∞，产生 NaN 错误。因此，我们使用 np.clip() 限制 y_pred
    - 防止梯度爆炸：在梯度更新时，梯度可能会变得非常大，导致参数更新过大，模型训练不稳定。我们可以用 np.clip() 限制梯度值

In [7]:
y_pred = np.array([0.0, 0.5, 1.0])
y_pred = np.clip(y_pred, 1e-12, 1.0)  # 限制在 [1e-12, 1.0]
print(y_pred)  # [1.e-12 5.e-01 1.e+00]

gradients = np.array([-100, -5, 0, 5, 100])
clipped_gradients = np.clip(gradients, -10, 10)
print(clipped_gradients)  # [-10  -5   0   5  10]

[1.e-12 5.e-01 1.e+00]
[-10  -5   0   5  10]


* **np.clip() vs np.maximum() 和 np.minimum()** <br>
np.clip(arr, a_min, a_max) =等价= np.minimum(np.maximum(arr, a_min), a_max)

In [ ]:
arr = np.array([-5, 0, 5, 10, 15])
print(np.clip(arr, 0, 10))   # [ 0  0  5 10 10 ]
print(np.minimum(np.maximum(arr, 0), 10))  # [ 0  0  5 10 10 ]

## np.esy(x)  # 单位矩阵  -> one-hot编码的标签

- NumPY
    - np.eyes(x)  # 单位矩阵  -> one-hot编码的标签

(numpy.bitcount() 是 NumPy 库中的一个函数，用于计算一个整数的二进制表示中 1 的个数。这个函数在处理位操作和二进制数据时非常有用。)

```python
numpy.bitcount(x, *, minlength=None)
```

- 参数说明
    - x: 输入的整数，可以是单个整数或整数数组。
    - minlength (可选): 如果指定，返回的数组将至少有 minlength 个元素。如果输入数组的长度小于 minlength，则会在前面填充零。
- 返回值
    - 对于单个整数输入，返回该整数的二进制表示中 1 的个数。
    - 对于整数数组输入，返回一个数组，其中每个元素是对应输入数组元素的二进制表示中 1 的个数。


In [1]:
import numpy as np 

np.__version__

'1.25.2'

## np.bincount(x)  # 计算 0 1 2 3 4   出现的次数

```python
numpy.bincount(x, *, minlength=None, maxlength=None)
```
- 参数说明
    - x: 输入的非负整数数组。数组中的元素必须是非负整数。
    - minlength (可选): 如果指定，返回的数组将至少有 minlength 个元素。如果输入数组中的最大值小于 minlength，则会在前面填充零。
    - maxlength (可选): 如果指定，返回的数组将最多有 maxlength 个元素。如果输入数组中的最大值大于 maxlength，则会引发 ValueError。
- 返回值
    - 返回一个一维数组，其中索引 i 处的值表示输入数组中值为 i 的元素个数。


In [9]:
x = np.array([2,12,31,3,14,1,4,5,45,3,5,3,5,35,3]).astype(np.uint8)
np.bincount(x)

array([0, 1, 1, 4, 1, 3, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1], dtype=int64)

In [10]:
np.bincount(x, minlength=len(x))

array([0, 1, 1, 4, 1, 3, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1], dtype=int64)

## 大范围数值-> 小范围数值 需要注意是否超出小范围

In [18]:
import PIL.Image as Image   
impath = r"../zzzz_code/sucai/msk3.png"
msk = np.array(Image.open(impath)).astype(np.uint8)

np.bincount(msk.reshape([-1]), minlength=128)[:5]

array([6589332,  160233,     435,       0,       0], dtype=int64)

In [19]:
np.bincount(np.reshape(msk, -1), minlength=100)[:5]

array([6589332,  160233,     435,       0,       0], dtype=int64)

In [20]:
np.bincount(np.reshape(msk, [-1]), minlength=100)[:5]

array([6589332,  160233,     435,       0,       0], dtype=int64)


```python 
- np.array type
    - np.int8  np.int16   有符号，可以负的
    - np.uin8   u表示无符号, 非负
```

- 有符号整数 (Signed Integer)
    - 定义: 有符号整数可以表示正数、负数和零。
    - 表示方法: 通常使用最高位（最左边的位）作为符号位，0 表示正数，1 表示负数。其余位表示数值的大小。
    - 范围: 例如，对于 8 位有符号整数 (np.int8)，其范围是 -128 到 127。
    - 用途: 适用于需要表示负数的场景，例如温度变化、财务数据等。
- 无符号整数 (Unsigned Integer)
    - 定义: 无符号整数只能表示非负数（包括零）。
    - 表示方法: 所有位都用于表示数值的大小，没有专门的符号位。
    - 范围: 例如，对于 8 位无符号整数 (np.uint8)，其范围是 0 到 255。
    - 用途: 适用于不需要表示负数的场景，例如图像处理中的像素值、计数器等。

- 转换注意事项
    - 从有符号到无符号: 如果将有符号整数转换为无符号整数，负数会被解释为非常大的正数。例如，np.int8 的 -1 转换为 np.uint8 后会变成 255。
    - 从无符号到有符号: 如果将无符号整数转换为有符号整数，大于等于最大正数的值会被解释为负数。例如，np.uint8 的 255 转换为 np.int8 后会变成 -1。

In [26]:
nnp =  np.bincount(msk.reshape([-1]), minlength=128)[:5]
print(f"{nnp = }")

nnp = array([6589332,  160233,     435,       0,       0], dtype=int64)


In [ ]:
nnp_uint8 = nnp.astype(np.uint8)[:5]  # int64 -> uint8 
nnp_uint8

array([148, 233, 179,   0,   0], dtype=uint8)

数据类型解释

- np.uint8:
    - 描述: 无符号 8 位整数。
    - 范围: 0 到 255。
    - 用途: 常用于图像处理，因为大多数图像的像素值在 0 到 255 之间。
- np.uint16:
    - 描述: 无符号 16 位整数。
    - 范围: 0 到 65535。
    - 用途: 用于需要更大范围的无符号整数的场景，例如某些科学数据或高精度图像处理。
- np.int8:
    - 描述: 有符号 8 位整数。
    - 范围: -128 到 127。
    - 用途: 用于需要小范围有符号整数的场景。
- np.int16:
    - 描述: 有符号 16 位整数。
    - 范围: -32768 到 32767。
    - 用途: 用于需要更大范围的有符号整数的场景。
- np.int32:
    - 描述: 有符号 32 位整数。
    - 范围: -2147483648 到 2147483647。
    - 用途: 用于大多数通用计算场景。
- np.int64:
    - 描述: 有符号 64 位整数。
    - 范围: -9223372036854775808 到 9223372036854775807。
    - 用途: 用于需要非常大范围的有符号整数的场景，例如某些科学计算或大数据处理。
- np.float32:
    - 描述: 单精度浮点数。
    - 范围: 大约 ±3.4e38，精度约为 7 位小数。
    - 用途: 用于需要浮点数但内存占用较小的场景。
- np.float64:
    - 描述: 双精度浮点数。
    - 范围: 大约 ±1.8e308，精度约为 16 位小数。
    - 用途: 用于大多数需要高精度浮点数的场景。

In [ ]:
# 就简单分析一下  大范围数值 -> 小范围数值 会发上什么

a = np.array([128], dtype=np.int64)
print(f"{a = }")
a_uint8 = a.astype(np.uint8)
print(f"{a_uint8 = }")
a_int8 = a.astype(np.int8)  # np.in8 scale:
[-128, 127]
print(f"{a_int8 = }")

a = array([128], dtype=int64)
a_uint8 = array([128], dtype=uint8)
a_int8 = array([-128], dtype=int8)


In [39]:
# np.intx  范围 [-2^(x/2)+1, 2^(x/2)-1]
# np.uintx 范围 [0, 2^x - 1]

# input_a largeScale -> result_a smallScale
# 好像就是 result_a = list(range(smallScale+1))[largeScale%smallScale_max_u] - 
input_a = 128
largeScale = (2**8) - 1 # np.uint8 scale
smallScale_min_u = -(2**4)+1  
smallScale_max_u = (2**4)-1

result_a = [x-128 for x in list(range(largeScale+1))][input_a%smallScale_max_u]
print(f"{result_a = }")
print(f"{list(range(largeScale+1)) = }")
print(f"{[x-128 for x in list(range(largeScale+1))] = }")
print(f"{largeScale%smallScale_max_u = }")

result_a = -120
list(range(largeScale+1)) = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 

## 计算 seg_pred == mask  需要注意numpy广播机制

In [20]:
y_label = np.array([[1],[0],[2],[3],[4],[2],[5],[6],[9]])
preds = np.array([1,0,2,3,4,2,5,6,9])

In [21]:
(y_label == preds).sum()  # 广播机制

11

In [22]:
(y_label.reshape([-1]) == preds).sum()

9

# **NumPY基础** 

- NumPy（ Numerical Python ）是一个开源 Python 库，几乎用于所有科学和工程领域。它是使用 Python 处理数值数据的通用标准，也是科学 Python 和 PyData 生态系统的核心。NumPy 用户包括从初级程序员到从事最先进科学和工业研究与开发的经验丰富的研究人员的所有人。NumPy API 广泛应用于 Pandas、SciPy、Matplotlib、scikit-learn、scikit-image 和大多数其他数据科学和科学 Python 包中。
```python
# 安装 pip install numpy   conda install numpy 

# 导入
import numpy as np  

# 查看numpy版本
np.__version__

* NumPy 库包含多维数组和矩阵数据结构 。它提供 ndarray ，一个同质的 n 维数组对象，具有对其进行有效操作的方法。NumPy 可用于对数组执行各种数学运算。它为 Python 添加了强大的数据结构，可确保使用数组和矩阵进行高效计算，并提供了一个庞大的高级数学函数库，可对这些数组和矩阵进行操作。

In [2]:
import numpy as np
arr1 = np.array([1,2,3])
print(f"{arr1 = }")
print(f"{type(arr1) = }")

arr1 = array([1, 2, 3])
type(arr1) = <class 'numpy.ndarray'>


- Python的列表和NumPY数组有什么区别？
    - NumPy 提供了大量快速有效的方法来创建数组并在其中操作数值数据。虽然 Python 列表可以在单个列表中包含不同的数据类型，但 NumPy 数组中的所有元素都应该是同质的。如果数组不是同质的，那么在数组上执行的数学运算将极其低效。
    - NumPy 数组比 Python 列表更快、更紧凑。数组占用的内存更少，使用起来更方便。NumPy 使用更少的内存来存储数据，并且它提供了指定数据类型的机制。这允许进一步优化代码。


- 什么是NumPY数组
    - 数组array是 NumPy 库的核心数据结构。数组是一个值网格，它包含有关原始数据、如何定位元素以及如何解释元素的信息。它有一个元素网格，可以以各种方式进行索引。所有元素都属于同一类型，称为数组dtype 。(n维数组 ndarray)
    - 数组可以通过非负整数元组、布尔值、另一个数组或整数进行索引。初始化 NumPy 数组的一种方法是通过 Python 列表，使用嵌套列表来处理二维或更高维数据。

In [3]:
a = np.array([1,2,4,5])  
b = np.array([[1,2],[2,3],[4,5]])  
print(f"{a[1] = }") # a[1] = 2   
print(f"{b[0] = }") # b[0] = array([1, 2])  
print(f"{type(a) = }") # type(a) = <class 'numpy.ndarray'>
print(f"{type(b) = }") # type(b) = <class 'numpy.ndarray'>

a[1] = 2
b[0] = array([1, 2])
type(a) = <class 'numpy.ndarray'>
type(b) = <class 'numpy.ndarray'>


- N 维数组
    - “ndarray”，这是“N 维数组”的简写。N 维数组只是一个具有任意数量维度的数组。您可能还会听到1-D或一维数组、 2-D或二维数组等等。NumPy ndarray类用于表示矩阵和向量。向量是具有单个维度的数组（行向量和列向量之间没有区别），而矩阵是指具有两个维度的数组。对于3-D或更高维的数组，术语 张量也很常用。

- **NumPY数组的基本属性**
    - 数组通常是固定大小的容器，包含相同类型和大小的项目。数组中的维度和项目数量由其形状定义。数组的形状是一组非负整数，用于指定每个维度的大小。在 NumPy 中，维度称为轴。


In [4]:
print(f"{a.shape = }") # a.shape = (4,)
print(f"{b.shape =}")  # b.shape =(3, 2)

a.shape = (4,)
b.shape =(3, 2)


数组b有2个轴（axis）， 第一个轴长度是3，第二个轴长度是2。NumPY数组的基本属性还有

In [5]:
print(f"{b.ndim = }")   # 维度的数量 b.ndim = 2
print(f"{b.size = }")   # 元素总数  b.size = 6
print(f"{b.dtype = }")  # 数据类型  b.dtype = dtype('int32')
print(f"{b.itemsize = }") # 每个元素的字节大小  b.itemsize = 4

b.ndim = 2
b.size = 6
b.dtype = dtype('int32')
b.itemsize = 4


与其他 Python 容器对象一样，可以通过索引或切片来访问和修改数组的内容。与典型的容器对象不同，不同的数组可以共享相同的数据，因此对一个数组所做的更改可能会在另一个数组中可见。

- NumPY 的副本和视图
    - 副本是一个数据的完整的拷贝，如果我们对副本进行修改，它不会影响到原始数据，物理内存不在同一位置。调用ndarray类的copy（）函数会产生一个副本，类似的还有python中的deepcopy（）函数。
    - 视图是数据的一个别称或引用，通过该别称或引用亦便可访问、操作原有数据，但原有数据不会产生拷贝。调用ndarray类的view（）函数会创建数组的视图，切片操作也会返回原数据的视图。

In [6]:
print(f"{b = }")  # b = array([[1, 2],[2, 3],[4, 5]])

bb = b # 无复制
b_view = b.view()  # 视图或浅拷贝
b_copy = b.copy()  # 副本或深拷贝
b_slice = b[0:1]   # 切片， b的(部分)视图 

print(f"{id(b) = }")
print(f"{id(bb) = }")
print(f"{id(b_view) = }")
print(f"{id(b_copy) = }")
print(f"{id(b_slice) = }")

print(f"{ (id(b) == id(bb)) = }")     # True
print(f"{(id(b) == id(b_view)) = }") # False
print(f"{  (id(b) == id(b_copy)) = }")  # False
print(f"{(id(b) == id(b_slice)) = }")  # False

b = array([[1, 2],
       [2, 3],
       [4, 5]])
id(b) = 1936709832016
id(bb) = 1936709832016
id(b_view) = 1936049741648
id(b_copy) = 1936709834032
id(b_slice) = 1936709834320
 (id(b) == id(bb)) = True
(id(b) == id(b_view)) = False
  (id(b) == id(b_copy)) = False
(id(b) == id(b_slice)) = False


In [7]:
# b 改变： b[0] + 1  # 这里其实就应用了numpy的广播机制，将1调整为b[0]的形状[1,1]，然后加
b[0]+=1
print(f"{b = }")  # change

print(f"{bb =}")  # change 
print(f"{b_view = }")  # change b的视图 跟python的copy(浅拷贝)一样，嵌套结构内的元素会跟着改变 
print(f"{b_slice = }") # change b的一部分视图

print(f"{b_copy = }")  # --

b = array([[2, 3],
       [2, 3],
       [4, 5]])
bb =array([[2, 3],
       [2, 3],
       [4, 5]])
b_view = array([[2, 3],
       [2, 3],
       [4, 5]])
b_slice = array([[2, 3]])
b_copy = array([[1, 2],
       [2, 3],
       [4, 5]])


In [8]:
bb[0] -= 1
print(f"{bb =}")  # change

print(f"{b = }")  # change
print(f"{b_view = }")  # change 
print(f"{b_slice = }") # change

print(f"{b_copy =}")  # --

bb =array([[1, 2],
       [2, 3],
       [4, 5]])
b = array([[1, 2],
       [2, 3],
       [4, 5]])
b_view = array([[1, 2],
       [2, 3],
       [4, 5]])
b_slice = array([[1, 2]])
b_copy =array([[1, 2],
       [2, 3],
       [4, 5]])


In [9]:
b_view[0] += 2  # 视图
print(f"{b_view = }") # change

print(f"{bb =}")  # change
print(f"{b = }")  # change
print(f"{b_slice = }") # change

print(f"{b_copy =}")  # --

b_view = array([[3, 4],
       [2, 3],
       [4, 5]])
bb =array([[3, 4],
       [2, 3],
       [4, 5]])
b = array([[3, 4],
       [2, 3],
       [4, 5]])
b_slice = array([[3, 4]])
b_copy =array([[1, 2],
       [2, 3],
       [4, 5]])


In [10]:
b_slice -= 8  # 视图
print(f"{b_slice = }") # change

print(f"{bb =}")  # change
print(f"{b = }")  # change
print(f"{b_view = }")  # change
print(f"{b_copy =}")  # --

b_slice = array([[-5, -4]])
bb =array([[-5, -4],
       [ 2,  3],
       [ 4,  5]])
b = array([[-5, -4],
       [ 2,  3],
       [ 4,  5]])
b_view = array([[-5, -4],
       [ 2,  3],
       [ 4,  5]])
b_copy =array([[1, 2],
       [2, 3],
       [4, 5]])


In [11]:
b_copy[0] += 2
print(f"{b_copy =}")  # change

print(f"{bb =}")  # --
print(f"{b = }")  # --
print(f"{b_view = }")  # --
print(f"{b_slice = }") # --

b_copy =array([[3, 4],
       [2, 3],
       [4, 5]])
bb =array([[-5, -4],
       [ 2,  3],
       [ 4,  5]])
b = array([[-5, -4],
       [ 2,  3],
       [ 4,  5]])
b_view = array([[-5, -4],
       [ 2,  3],
       [ 4,  5]])
b_slice = array([[-5, -4]])


- 赋值（=）不会创建副本，而是让变量指向相同的数据。修改其中一个变量的值会影响另一个，因为它们共享同一块内存。。 
- ndarray.view() 创建一个新的数组对象，但数据仍然共享相同的物理内存。view() 不能修改原数组的形状，但 reshape() 可以重新组织视图的数据。
- 切片（slice）通常返回视图，而不是副本。修改切片的数据会影响原数组

In [12]:
# reshape 改变数组形状
g = np.arange(6).reshape(3,2)
print(f"{g.shape = }") # g.shape = (3, 2)
h = np.reshape(g, newshape=(1,6))
print(f"{h.shape = }") # h.shape = (1, 6)
print(f"{g.shape = }") # g.shape = (3, 2)

g.shape = (3, 2)
h.shape = (1, 6)
g.shape = (3, 2)


In [ ]:
print(f"{id(g) == (id(np.reshape(g, newshape=(1,6))))}")  # false 
# np.reshape()  返回一个新的数组对象

l = g.view()
l = l.reshape((1,6))    #  reshape操作创造的新对象覆盖了原来的 l ， 这个l已经不再是g的视图了
print(f"{g.shape = }") # g.shape = (3, 2)
print(f"{l.shape = }") # l.shape = (1, 6)

False
g.shape = (3, 2)
l.shape = (1, 6)


增加一个轴 np.newaxis

In [14]:
m = g[-1]
print(f"{type(m) = }")  # <class 'numpy.ndarray'>
print(f"{m = }")  # m = array([4, 5])
print(f"{m.shape = }")  # m.shape = (2,)

m = m[np.newaxis, :]
print(f"{m.shape = }")  # m.shape = (1, 2)
print(f"{g.shape = }")  # g.shape = (3, 2)

type(m) = <class 'numpy.ndarray'>
m = array([4, 5])
m.shape = (2,)
m.shape = (1, 2)
g.shape = (3, 2)


In [ ]:
m = np.array([[0,1], [0,1]])  # 这个新的数组对象覆盖了原本的m
print(f"{m.shape = }") # (2, 2)  # 此时的m已经不再是g的视图了
print(f"{g.shape = }"),
print(f"{g = }")

## **创建NumPY数组**

In [15]:
np.zeros((2, 3))       # 2x3 的全零数组
np.ones((3, 2))        # 3x2 的全 1 数组
np.full((3, 3), 3)     # 3x3 的全 3 数组
np.eye(4)              # 4x4 单位矩阵
np.arange(0, 10, 2)    # [0, 2, 4, 6, 8]
np.linspace(0, 1, 5)   # 生成 5 个等间距点 [0.  0.25  0.5  0.75  1.]
np.random.rand(2, 3)   # 2x3 的随机浮点数 (0,1)

array([[0.55570503, 0.91012595, 0.35410153],
       [0.13410813, 0.06841282, 0.74581195]])

指定数据类型

In [16]:
x = np.ones(3, dtype=np.int64)
print(f"{x = }")  # x = array([1, 1, 1], dtype=int64)

x = array([1, 1, 1], dtype=int64)


数据类型转换

In [17]:
y= np.array([1.2, 3.4, 128.], dtype=np.float32)
y1=y.astype('int8') # 有符号8位整数，数据范围[-2*7-1, 2*7] [-128,127]
print(f"{y1 = }")  # y1 = array([1, 3, -128], dtype=int8)
# 数据范围大的array转换成数据范围小的需要考虑，是否超出数据范围， 
 
y2=y.astype(np.uint8) # u表示无符号，uint8数据范围[0,255]
print(f"{y2 = }") # y2 = array([  1,   3, 128], dtype=uint8)

# astype 返回一个新的对象
y= np.array([1.2, 3.4, 128.], dtype=np.float32)
origin_ = id(y)
new_ = id(y.astype('float32'))
print((origin_ == new_))  # False
print(f"{y.dtype = }") # y.dtype = dtype('float32') 

y1 = array([   1,    3, -128], dtype=int8)
y2 = array([  1,   3, 128], dtype=uint8)
False
y.dtype = dtype('float32')


## **用随机数创建数组**

In [18]:
np.random.seed(42)  # 固定随机数种子
np.random.rand(3, 3)  # (0,1) 均匀分布
np.random.randn(3, 3) # 标准正态分布
np.random.uniform(low=0.0, high=1.0, size=(2,3))  # (low, high) 均匀分布
np.random.randint(1, 10, (3, 3))  # 整数随机数
np.random.choice([1, 2, 3, 4], size=5)  # 从列表中随机抽取

array([1, 4, 2, 2, 2])

In [19]:
k = np.random.choice([1, 2, 3, 4], size=5)
print(k)
z = np.random.choice([1, 2, 3, 4, 5], size=(2,3)) 
print(f"{z =}")# z =array([[5, 5, 4],[3, 1, 5]])


[1 2 1 2 4]
z =array([[4, 4, 4],
       [5, 3, 1]])


## 添加

- 数组操作：添加、删除、排序元素、堆叠、拼接
    - append() 添加元素
    - delete() 删除元素
    - sort() 排序数组
    - concatenate() 连接数组
    - stack() 垂直/水平堆叠

NumPy 不支持动态扩展数组，但可以使用 np.append() 创建新数组。展平然后append

In [17]:
arr_1  = np.random.randint(1,9,(1,9))
arr_1_new = np.append(arr_1, [13,12])
print(f"{arr_1 =}")
print(f"{arr_1_new =}")
print(f"{arr_1_new.shape = }")

arr_1 =array([[1, 2, 3, 7, 5, 1, 7, 5, 7]])
arr_1_new =array([ 1,  2,  3,  7,  5,  1,  7,  5,  7, 13, 12])
arr_1_new.shape = (11,)


In [14]:
arr_1_nnew  =  np.append(arr_1, [[13],[12]])
print(f"{arr_1_nnew.shape = }")

arr_1_nnew.shape = (11,)


In [16]:
arr_1_b = np.random.rand(2,4)
print(f"{arr_1_b = }")
arr_1b_new =  np.append(arr_1_b, [1,1,1,1])
print(f"{arr_1b_new.shape = }")

arr_1_b = array([[0.02714552, 0.06061306, 0.33529343, 0.70582807],
       [0.80199368, 0.09351011, 0.12576481, 0.07568549]])
arr_1b_new.shape = (12,)


In [13]:
arr_1_c = np.random.rand(2,4,3)  
arr_1c_new =  np.append(arr_1_c, [4,4,4])
print(f"{arr_1c_new.shape =}")

arr_1c_new.shape =(27,)


In [22]:
arr_1_cc =  np.full((4,3), 3)
print(arr_1_cc)
arr_1c_nnew  = np.append(arr_1_c, arr_1_cc)
print(f"{arr_1c_nnew.shape = }")

[[3 3 3]
 [3 3 3]
 [3 3 3]
 [3 3 3]]
arr_1c_nnew.shape = (36,)


## 删除

In [25]:
arr3 = np.random.randn(2,1)
print(f"{arr3.shape = }")
arr3_new = np.delete(arr3, -1)
print(f"{arr3_new = }")

arr3.shape = (2, 1)
arr3_new = array([-0.49671453])


In [28]:
arr3_b = np.random.uniform(0,1,(2,2,2))  
print(f"{arr3_b = }")
arr3_b_new = np.delete(arr3_b, 1)
print(f"{arr3_b_new = }")

arr3_b = array([[[0.24929825, 0.70515476],
        [0.83537686, 0.8429821 ]],

       [[0.94529383, 0.27315047],
        [0.7168798 , 0.84745712]]])
arr3_b_new = array([0.24929825, 0.83537686, 0.8429821 , 0.94529383, 0.27315047,
       0.7168798 , 0.84745712])


## 排序元素  升序

In [30]:
arr4  =  np.random.randint(1,4, [3,4])
arr4_new =  np.sort(arr4) # axis=0
print(f"{arr4_new.shape = }")
print(f"{arr4_new = }")

arr4_new.shape = (3, 4)
arr4_new = array([[1, 2, 3, 3],
       [1, 1, 2, 3],
       [1, 1, 3, 3]])


## 堆叠

In [46]:
arr5_a = np.zeros((2,3,2))
arr5_b  =  np.ones((1,3,2))  # axis1 axis2  相同。 只能沿着axis0 方向 拼接
arr5_A0  = np.concatenate((arr5_a, arr5_b), axis=0)
print(f"{arr5_A0.shape = }")
print(f"{arr5_A0 = }") # 3,3,2  

arr5_c  = np.full((2,1,2), 2)  # axis0 axis2  相同 ，只能沿着axis=1方向拼接
arr5_A1  = np.concatenate((arr5_a, arr5_c), axis=1)
print(f"{arr5_A1.shape = }")
print(f"{arr5_A1 = }")  # 2，4，2   


arr5_d  = np.full((2,3,1), 3)  # axis0 axis1  相同 ，只能沿着axis=2方向拼接
arr5_A2  = np.concatenate((arr5_a, arr5_d), axis=2)
print(f"{arr5_A2.shape = }")
print(f"{arr5_A2 = }")  # 2，4，2  

arr5_A0.shape = (3, 3, 2)
arr5_A0 = array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])
arr5_A1.shape = (2, 4, 2)
arr5_A1 = array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [2., 2.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [2., 2.]]])
arr5_A2.shape = (2, 3, 3)
arr5_A2 = array([[[0., 0., 3.],
        [0., 0., 3.],
        [0., 0., 3.]],

       [[0., 0., 3.],
        [0., 0., 3.],
        [0., 0., 3.]]])


## 拼接

In [40]:
arr6_a = np.zeros_like([[1],[2]])  # (2,1)
print(f"{arr6_a.shape = }")
print(f"{arr6_a = }")
arr6_b = np.ones((2,1))
print(arr6_b.shape)
arr6_c = np.ones_like((2,)) # 
print(f"{arr6_c = }")

arr6_h  =  np.hstack((arr6_a, arr6_b))  # 口口
arr6_v  =  np.vstack((arr6_a, arr6_c))  #  =
print(f"{arr6_h = }")
print(f"{arr6_h.shape = }")
print(f"{arr6_v = }")
print(f"{arr6_v.shape = }")  # arr6_v.shape = (3, 1)

arr6_a.shape = (2, 1)
arr6_a = array([[0],
       [0]])
(2, 1)
arr6_c = array([1])
arr6_h = array([[0., 1.],
       [0., 1.]])
arr6_h.shape = (2, 2)
arr6_v = array([[0],
       [0],
       [1]])
arr6_v.shape = (3, 1)


## reshape

- reshape  arr.reshape((x,x,x,))  arr_new= np.reshape
- 展平 .reshape(-1)  .flatten()   .reval()

##  维度扩展， np.newaxis
- arr=np.array([1,2]) arr_new = arr[:,np.newaxis] -> arr_new = [[1,2]]

In [48]:
arrkz = np.array([1,2])
arrkz_n = arrkz[:,np.newaxis]
print(f"{arrkz_n = }")  # array([[1], [2]])
print(f"{arrkz_n.shape = }") # (2,1)


arrkz_new = arrkz[np.newaxis,:]
print(f"{arrkz_new = }")  # arrkz_new = array([[1, 2]])
print(f"{arrkz_new.shape = }")  # arrkz_new.shape = (1, 2)

arrkz_n = array([[1],
       [2]])
arrkz_n.shape = (2, 1)
arrkz_new = array([[1, 2]])
arrkz_new.shape = (1, 2)


##  ravel() 和 flatten() 展平数组

In [49]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr.ravel())    # [1 2 3 4 5 6]
print(arr.flatten())  # [1 2 3 4 5 6]

[1 2 3 4 5 6]
[1 2 3 4 5 6]


## 基本索引

In [12]:
import numpy as np 
arr1 = np.array([[2,2,2,2,0]])
print(f"{len(arr1) = }")
print(f"{arr1.shape = }")
arr1[0][1]

len(arr1) = 1
arr1.shape = (1, 5)


2

In [11]:
arrb = np.array([[1,1,1,1,0],[2,2,2,2,0]])
- 一维数组ar 
    - ar[idx]
    - ar[a:b] [idx=a -> idx=b)
- 二维数组arr 
    - arr[:,1] 取第idx=1这列  arr[1,1] 取第idx=1 这行这列 
    - arr[a:b, ]  ...
- 三维数组arrr 
    - arrr[:,:,1]   ...
    - arrr[a:b,:,:]   ...


IndexError: too many indices for array: array is 2-dimensional, but 4 were indexed

## 布尔索引

In [50]:
arr = np.array([1, 2, 3, 4, 5])
print(arr[arr > 2])  # [3 4 5]

[3 4 5]


In [ ]:
# 二维数组中
arr = np.array([[1, 2, 3], 
                [4, 5, 6], 
                [7, 8, 9]])

print(arr[arr > 5])  # [6 7 8 9]

## 花式索引

In [51]:
arr = np.array([10, 20, 30, 40])
index = [0, 2, 3]
print(arr[index])  # [10 30 40]

[10 30 40]


In [1]:
# 花式索引也适用于多维数组

arr = np.array([[10, 20, 30], 
                [40, 50, 60], 
                [70, 80, 90]])

rows = [0, 1, 2]
cols = [2, 1, 0]

print(arr[rows, cols])  # [30 50 70]

NameError: name 'np' is not defined

##  where() 条件索引

In [52]:
arr = np.array([10, 20, 30, 40])
print(np.where(arr > 20))  # (array([2, 3]),)

(array([2, 3], dtype=int64),)


In [53]:
# 函数 
arr = np.array([1, 2, 3, 4])
print(np.sum(arr))  # 10
print(np.mean(arr)) # 2.5
print(np.max(arr))  # 4

10
2.5
4


## 广播机制
- 当数组形状不同但可以匹配时，NumPy 自动扩展较小的数组
    - 从右向左对齐形状（即最后一个维度先对齐）
    - 如果某个维度的大小相同，或其中一个为 1，则可以广播。
    - 如果维度不匹配且都不为 1，则无法广播，会报错


```python
# arr 可以匹配那些shape的数组  -- 支持广播
ndarray.shape = (a, b, c) 
    - np.array([int])  # shape (1,)
    - np.array([...])  # shape (c,)
    - shape (1,c)
    - shape (b,c)
    - shape(1,b,c)
    - shape(a,b,c)
    - shape(1,a,b,c)
    - shape(...,a,b,c)


In [55]:
1+ np.array([[0,0],[0,0]])

array([[1, 1],
       [1, 1]])

In [58]:
arrx = np.zeros((2,3,4))  # shape(a,b,c)

arrx   + np.ones_like([2])     # (1,)
arrx   + np.arange(4)          # (c,)
arrx   + np.zeros((1,4))       # (1,c)
arrx   + np.zeros((3,4))       # (b,c)
arrx   + np.zeros((1,3,4))     # (1,b,c)
arrx   + np.zeros((2,3,4))     # (a,b,c)
arrx   + np.zeros((1,2,3,4))   # (1,a,b,c)
arrx   + np.zeros((1,2,2,3,4)) # (..., a, b, c)

array([[[[[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]],

         [[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]]],


        [[[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]],

         [[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]]]]])