In [2]:
import torch
x = torch.arange(4.0)
x

tensor([0., 1., 2., 3.])

In [3]:
x.requires_grad_(True)
x.grad # None

In [6]:
# x.grad.zero_()  # 'NoneType' object has no attribute 'zero_'
# x.grad

y=x.sum()
y

tensor(6., grad_fn=<SumBackward0>)

In [7]:
y.backward()
x.grad

tensor([1., 1., 1., 1.])

In [9]:
x.grad.zero_()
y = x * x 
y.sum().backward()   # y.backward(torch.ones(len(x)))
x.grad

tensor([0., 2., 4., 6.])

In [10]:
x.grad.zero_()
y = x * x
u = y.detach()
z = u * x

z.sum().backward()
x.grad == u

tensor([True, True, True, True])

In [11]:
x.grad.zero_()
y.sum().backward()
x.grad == 2 * x

tensor([True, True, True, True])

In [12]:
def f(a):
    b = a * 2
    while b.norm() < 1000:
        b = b * 2
    if b.sum() > 2:
        c = b
    else:
        c = 100 * b
    return c

a = torch.randn(size=(), requires_grad=True)
d = f(a)
d.backward()

a.grad == d / a
    

tensor(True)

In [ ]:
def sgd(params, lr, batch_size):
    # mini batch sgd
    with torch.no_grad():
        for param in params:
            param -= lr * param.grad / batch_size
            param.grad.zero_()

# trainer = torch.optims.SGD(net.parameters(), lr=0.03)

In [ ]:
def softmax(x):
    x_exp = torch.exp(x)
    partition = x_exp.sum(1, keepdim=True)
    return x_exp / partition

In [ ]:
num_inputs, num_outputs, num_hiddens = 784, 10, 256

w1 = torch.nn.Parameter(torch.randn(num_inputs, num_hiddens, requires_grad=True))
b1 = torch.nn.parameter(torch.zeros(num_hiddens, requires_grad=True))
w2 = torch.nn.parameter(torch.randn(num_hiddens, num_outputs, requires_grad=True))
b2 = torch.nn.parameter(torch.zeros(num_outputs, requires_grad=True))
params = [w1, b1, w2, b2]

def relu(x):
    a = torch.zeros_like(x)
    return torch.max(a, 0)

def net(x):
    x = x.reshape(-1, num_inputs)
    H = relu(x@w1 + b1)
    return (H@w1 + b2)

In [ ]:
def dropout_layer(x, dropout):
    assert 0 <= dropout <= 1
    
    if dropout == 1:
        return torch.zeros_like(x)
    
    if dropout == 0:
        return x
    
    mask = (torch.rand(x.shape) > dropout).float()
    
    return mask * x / (1-dropout)
    